version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672" # management UI: http://localhost:15672 (guest/guest)
    networks:
      - medica-network

  auth:
    build:
      context: ./services/auth
    env_file:
      - ./infra/.env.example
    environment:
      AUTH_PORT: 4001
    ports:
      - "4001:4001"
    depends_on:
      - rabbitmq
    networks:
      - medica-network

  cedula:
    build:
      context: ./services/cedula
    env_file:
      - ./infra/.env.example
    environment:
      CEDULA_PORT: 4003
    ports:
      - "4003:4003"
    depends_on:
      - rabbitmq
    networks:
      - medica-network

  expediente:
    build:
      context: ./services/expediente
    env_file:
      - ./infra/.env.example
    environment:
      EXPEDIENTE_PORT: 4002
    ports:
      - "4002:4002"
    depends_on:
      - rabbitmq
    networks:
      - medica-network

  gateway:
    build:
      context: ./services/gateway
    env_file:
      - ./infra/.env.example
    environment:
      GATEWAY_PORT: 4000
      AUTH_URL: http://auth:4001
      CEDULA_URL: http://cedula:4003
      EXPEDIENTE_URL: http://expediente:4002
      RABBITMQ_URL: amqp://rabbitmq
    ports:
      - "4000:4000"
    depends_on:
      - auth
      - cedula
      - expediente
      - rabbitmq
    networks:
      - medica-network

  websocket:
    build:
      context: ./services/websocket
    env_file:
      - ./infra/.env.example
    environment:
      WEBSOCKET_PORT: 4004
      RABBITMQ_URL: amqp://rabbitmq
    ports:
      - "4004:4004"
    depends_on:
      - rabbitmq
    networks:
      - medica-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_GATEWAY_URL: http://localhost:4000/api/gateway
    env_file:
      - ./infra/.env.example
    environment:
      PORT: 3000
      NEXT_PUBLIC_GATEWAY_URL: http://localhost:4000/api/gateway
    ports:
      - "3000:3000"
    depends_on:
      - gateway
    networks:
      - medica-network

networks:
  medica-network:
    driver: bridge
